Repository IntelRealSense/librealsense, pull requests merged in 2018-08, with the labels that each got.

#2130 Don't return the platform camera using default Query Devices
  CMake/realsense.def
  include/librealsense2/h/rs_context.h
  include/librealsense2/hpp/rs_context.hpp
  include/librealsense2/rs.h
  src/context.cpp
  src/context.h
  src/device_hub.cpp
  src/pipeline.cpp
  src/rs.cpp
  wrappers/csharp/Intel.RealSense/Context.cs
  wrappers/csharp/Intel.RealSense/NativeMethods.cs
  wrappers/python/python.cpp
Labels: enhancement

#2098 Wrapping Software Device for .NET
  wrappers/csharp/CMakeLists.txt
  wrappers/csharp/Intel.RealSense/CMakeLists.txt
  wrappers/csharp/Intel.RealSense/Device.cs
  wrappers/csharp/Intel.RealSense/Helpers.cs
  wrappers/csharp/Intel.RealSense/NativeMethods.cs
  wrappers/csharp/Intel.RealSense/Processing.cs
  wrappers/csharp/Intel.RealSense/Sensor.cs
  wrappers/csharp/Intel.RealSense/SoftwareDevice.cs
  wrappers/csharp/Intel.RealSense/Types.cs
  wrappers/csharp/cs-tutorial-4-software-dev/CMakeLists.txt
  wrappers/csharp/cs-tutorial-4-software-dev/Program.cs
  wrappers/csharp/cs-tutorial-4-software-dev/Window.xaml
  wrappers/csharp/cs-tutorial-4-software-dev/Window.xaml.cs
  wrappers/csharp/cs-tutorial-4-software-dev/app.config
Labels: .NET

#2154 Adding Two Dimensional Data Protocols for python wrapper (vtx & tex)
  wrappers/python/python.cpp
Labels: python
