Repository IntelRealSense/librealsense, pull requests merged in 2018-02, with the labels that each got.

#1193 Fix software device to enable recording into ROS-bag
  src/software-device.cpp
Labels: SDK 2.0

#1204 Unity Improvements
  wrappers/csharp/Intel.RealSense/Sensor.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Materials/BGSegMat.mat
  wrappers/unity/Assets/RealSenseSDK2.0/Prefabs/Images.prefab
  wrappers/unity/Assets/RealSenseSDK2.0/Prefabs/RealsenseDevice.prefab
  wrappers/unity/Assets/RealSenseSDK2.0/Scenes/RealSenseTextures.unity
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/DepthScale.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/GradientTexture.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/PointCloudGenerator.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/PointCloudGenerator.cs.meta
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RealSenseConfiguration.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RealSenseDevice.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RealSenseDeviceInspector.cs
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RealSenseDeviceInspector.cs.meta
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RealsenseStreamTexture.cs
  wrappers/unity/readme.md
Labels: .NET, unity

#1233 Allowing to call load_json on a recording device
  src/core/advanced_mode.h
  src/media/record/record_device.cpp
Labels: SDK 2.0, bug
