Repository IntelRealSense/librealsense, pull requests merged in 2018-12, with the labels that each got.

#2829 Emitter On/Off
  include/librealsense2/h/rs_option.h
  src/ds5/ds5-color.cpp
  src/ds5/ds5-device.cpp
  src/ds5/ds5-motion.cpp
  src/ds5/ds5-options.cpp
  src/ds5/ds5-options.h
  src/ds5/ds5-private.cpp
  src/ds5/ds5-private.h
  src/ds5/ds5-rolling-shutter.cpp
  src/types.cpp
  src/types.h
Labels: api_change

#2830 Export Processing blocks
  CMakeLists.txt
  include/CMakeLists.txt
  include/librealsense2/h/rs_processing.h
  include/librealsense2/hpp/rs_export.hpp
  include/librealsense2/hpp/rs_processing.hpp
  src/api.h
  src/option.cpp
  src/option.h
  src/realsense.def
  src/rs.cpp
  wrappers/matlab/librealsense_mex.cpp
  wrappers/matlab/options.m
  wrappers/matlab/save_single_frameset.m
  wrappers/matlab/save_to_ply.m
  wrappers/python/python.cpp
Labels: api_change

#2940 Windows hid gyro fix
  src/win/win-hid.cpp
  third-party/libtm/libtm/CMakeLists.txt
  third-party/libtm/resources/CMakeLists.txt
  third-party/libtm/versions.cmake
Labels: Windows, bug, d435i

#2959 Motion module GUI updates
  common/model-views.cpp
  common/model-views.h
  common/rendering.h
  src/tm2/tm-device.h
  third-party/libtm/tools/libtm_util/libtm_util.cpp
  third-party/libtm/versions.cmake
Labels: Windows, d435i

#2985 Win7 compilation fix
  .travis.yml
  src/win7/win7-backend.cpp
Labels: Windows, bug
