Repository IntelRealSense/librealsense, pull requests merged in 2018-10, with the labels that each got.

#2370 first commit of the OpenNI2 wrapper by the Palo Alto Group
  wrappers/openni2/.gitignore
  wrappers/openni2/CMakeLists.txt
  wrappers/openni2/README.md
  wrappers/openni2/doc/img/demo.jpg
  wrappers/openni2/doc/img/oni_capture.jpg
  wrappers/openni2/doc/img/oni_user.jpg
  wrappers/openni2/doc/img/oni_video_mode.jpg
  wrappers/openni2/doc/img/oni_viewer.jpg
  wrappers/openni2/src/D2S.h
  wrappers/openni2/src/Profiler.h
  wrappers/openni2/src/Profiler.inl
  wrappers/openni2/src/Rs2Base.cpp
  wrappers/openni2/src/Rs2Base.h
  wrappers/openni2/src/Rs2Device.cpp
  wrappers/openni2/src/Rs2Device.h
  wrappers/openni2/src/Rs2DeviceProps.cpp
  wrappers/openni2/src/Rs2Driver.cpp
  wrappers/openni2/src/Rs2Driver.h
  wrappers/openni2/src/Rs2Stream.cpp
  wrappers/openni2/src/Rs2Stream.h
  wrappers/openni2/src/Rs2StreamProps.cpp
  wrappers/openni2/src/S2D.h
Labels: openni

#2467 Added kernel patching scripts for OpenSuSE Leap 15.0 and Tumbleweed
  scripts/patch-opensuse-leap15.sh
  scripts/patch-opensusetumbleweed.sh
  scripts/realsense-camera-formats-opensuse.patch
Labels: Linux

#2490 Libuvc fixes
  src/libuvc/libuvc.cpp
  src/libuvc/libuvc.h
  wrappers/python/examples/python-rs400-advanced-mode-example.py
Labels: MacOS

#2491 Python wrapper tweaks
  wrappers/python/python.cpp
Labels: python

#2513 change message about frames coming in stop mode to INFO
  src/linux/backend-v4l2.cpp
Labels: ros

#2511 RGB sensor auto-exposure region of interest
  src/ds5/ds5-color.cpp
  src/ds5/ds5-color.h
  src/ds5/ds5-device.cpp
  src/ds5/ds5-device.h
  src/ds5/ds5-private.h
  wrappers/csharp/Intel.RealSense/Sensor.cs
Labels: D400 Series

#2492 Fix typos in matlab wrapper
  wrappers/matlab/MatlabParamParser.h
  wrappers/matlab/align.m
  wrappers/matlab/colorizer.m
  wrappers/matlab/config.m
  wrappers/matlab/decimation_filter.m
  wrappers/matlab/depth_sensor.m
  wrappers/matlab/depth_stereo_sensor.m
  wrappers/matlab/disparity_transform.m
  wrappers/matlab/frameset.m
  wrappers/matlab/hole_filling_filter.m
  wrappers/matlab/librealsense_mex.cpp
  wrappers/matlab/librealsense_mex.vcxproj
  wrappers/matlab/librealsense_mex.vcxproj.filters
  wrappers/matlab/pipeline_profile.m
  wrappers/matlab/pointcloud.m
  wrappers/matlab/process_interface.m
  wrappers/matlab/processing_block.m
  wrappers/matlab/roi_sensor.m
  wrappers/matlab/rs2_type_traits.h
  wrappers/matlab/spatial_filter.m
  wrappers/matlab/stream_profile.m
  wrappers/matlab/temporal_filter.m
  wrappers/matlab/types.h
Labels: matlab
