Repository IntelRealSense/librealsense, pull requests merged in 2019-10, with the labels that each got.

#4945 rs-ar-basic: fix extrinsic pose to camera transformation
  examples/ar-basic/readme.md
  examples/ar-basic/rs-ar-basic.cpp
Labels: tracking

#4936 Notification category for Relocalization
  include/librealsense2/h/rs_types.h
  src/tm2/tm-device.cpp
  src/tm2/tm-device.h
  src/types.cpp
  wrappers/csharp/Intel.RealSense/Types/Enums/NotificationCategory.cs
Labels: api_change

#4953 illustration for project
  doc/android.md
  doc/img/realsense-android.png
Labels: android, documentation
