Repository IntelRealSense/librealsense, pull requests merged in 2019-03, with the labels that each got.

#3337 android - frame metadata support added
  src/android/android-uvc.cpp
  src/android/android-uvc.h
  src/android/jni/frame.c
  src/android/usb_host/android_uvc.cpp
  src/android/usb_host/device_watcher.cpp
  src/android/usb_host/usb_device.cpp
  src/android/usb_host/usb_device.h
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DeviceWatcher.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Frame.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/FrameMetadata.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/TimestampDomain.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/DetachedActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/PreviewActivity.java
Labels: android

#3339 add API function unload_tracking_module.
  include/librealsense2/h/rs_context.h
  include/librealsense2/hpp/rs_context.hpp
  src/context.h
  src/realsense.def
  src/rs.cpp
Labels: T260 series, api_change, libtm

#3359 T265 readme updates
  doc/android.md
  doc/d435i.md
  doc/imu_and_tracking_sensors.md
  doc/installation_osx.md
  doc/readme.md
  doc/t265.md
  readme.md
Labels: documentation

#3318 Bug fixes
  common/model-views.cpp
  common/realsense-ui-advanced-mode.h
  common/rendering.h
  examples/example.hpp
  examples/pointcloud/rs-pointcloud.cpp
  examples/software-device/rs-software-device.cpp
  include/librealsense2/h/rs_context.h
  include/librealsense2/h/rs_sensor.h
  include/librealsense2/hpp/rs_context.hpp
  include/librealsense2/hpp/rs_internal.hpp
  include/librealsense2/hpp/rs_processing.hpp
  include/librealsense2/hpp/rs_sensor.hpp
  include/librealsense2/rs.h
  include/librealsense2/rsutil.h
  src/context.cpp
  src/context.h
  src/proc/disparity-transform.cpp
  src/proc/disparity-transform.h
  src/realsense.def
  src/rs.cpp
  src/software-device.cpp
  src/software-device.h
  tools/convert/converters/converter-ply.hpp
  tools/convert/rs-convert.cpp
  unit-tests/CMakeLists.txt
  unit-tests/unit-tests-post-processing.cpp
  unit-tests/unit-tests-post-processing.h
Labels: GUI, api_change, bug

#3324 Import/Export T265 localization map API
  common/model-views.cpp
  include/librealsense2/h/rs_frame.h
  include/librealsense2/h/rs_sensor.h
  include/librealsense2/h/rs_types.h
  include/librealsense2/hpp/rs_frame.hpp
  include/librealsense2/hpp/rs_sensor.hpp
  include/librealsense2/hpp/rs_types.hpp
  src/core/motion.h
  src/core/options.h
  src/core/streaming.h
  src/ds5/ds5-device.cpp
  src/ivcam/sr300.cpp
  src/l500/l500-private.cpp
  src/l500/l500.cpp
  src/option.h
  src/proc/decimation-filter.cpp
  src/realsense.def
  src/rs.cpp
  src/tm2/tm-context.cpp
  src/tm2/tm-device.cpp
  src/tm2/tm-device.h
  src/types.cpp
  src/types.h
  third-party/realsense-file/rosbag/cpp_common/include/ros/platform.h
  unit-tests/resources/calibration_odometry.json
  unit-tests/unit-tests-live.cpp
  wrappers/csharp/Intel.RealSense/Frames/FrameSet.cs
  wrappers/csharp/Intel.RealSense/NativeMethods.cs
  wrappers/python/CMakeLists.txt
  wrappers/python/examples/t265_example.py
  wrappers/python/pybackend.cpp
  wrappers/python/python.cpp
Labels: T260 series, api_change, tracking

#3366 Android - backend bug fixes and camera app new features
  src/android/jni/config.c
  src/android/usb_host/device_watcher.cpp
  src/android/usb_host/usb_device.cpp
  src/android/usb_host/usb_device.h
  src/android/usb_host/usb_pipe.cpp
  src/android/usb_host/usb_pipe.h
  wrappers/android/examples/capture/src/main/AndroidManifest.xml
  wrappers/android/examples/java_example/app/src/main/AndroidManifest.xml
  wrappers/android/examples/java_example/readme.md
  wrappers/android/examples/native_example/app/src/main/AndroidManifest.xml
  wrappers/android/examples/native_example/readme.md
  wrappers/android/examples/recording/src/main/AndroidManifest.xml
  wrappers/android/librealsense/src/main/AndroidManifest.xml
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Config.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DeviceWatcherActivity.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/RsContext.java
  wrappers/android/tools/camera/src/main/AndroidManifest.xml
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/CheckableTwoLinesListCell.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/CheckableTwoLinesListCellAdapter.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/DetachedActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/FileBrowserActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/PlaybackActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/PreviewActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/RecordingActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/SettingsActivity.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/Streamer.java
  wrappers/android/tools/camera/src/main/res/layout/activity_list_view.xml
  wrappers/android/tools/camera/src/main/res/layout/activity_preview.xml
  wrappers/android/tools/camera/src/main/res/layout/checkable_list_view.xml
  wrappers/android/tools/camera/src/main/res/layout/files_list_view.xml
  wrappers/android/tools/camera/src/main/res/values/strings.xml
Labels: android

#3340 API for adding software device into existing context
  include/librealsense2/hpp/rs_internal.hpp
  src/context.cpp
  src/context.h
  src/rs.cpp
  src/software-device.cpp
Labels: api_change

#3382 Merge changes from master to development branch
  doc/installation_osx.md
  doc/libuvc_installation.md
  examples/readme.md
  include/librealsense2/h/rs_context.h
  include/librealsense2/hpp/rs_context.hpp
  include/librealsense2/rs.h
  package.xml
  readme.md
  scripts/libuvc_installation.sh
  src/context.h
  src/realsense.def
  src/rs.cpp
  wrappers/matlab/readme.md
  wrappers/python/examples/python-rs400-advanced-mode-example.py
Labels: api_change

#3415 Adding D430i support for Linux
  config/99-realsense-libusb.rules
  scripts/realsense-metadata-ubuntu-bionic-master.patch
  scripts/realsense-metadata-ubuntu-xenial-Ubuntu-hwe-4.13.0-45.50_16.04.1.patch
  scripts/realsense-metadata-ubuntu-xenial-Ubuntu-hwe-4.8.0-58.63_16.04.1.patch
  scripts/realsense-metadata-ubuntu-xenial-hwe-zesty.patch
  scripts/realsense-metadata-ubuntu-xenial-hwe.patch
  scripts/realsense-metadata-ubuntu-xenial-master.patch
  scripts/realsense-metadata-ubuntu-xenial-v4.16.patch
  src/ivcam/sr300.cpp
  src/l500/l500.cpp
  src/linux/backend-v4l2.cpp
  src/media/ros/ros_reader.cpp
  src/media/ros/ros_writer.cpp
  src/proc/zero-order.cpp
Labels: Linux, d435i

#3399 Work in progress on Mac OS support for the T265
  CMake/apple_config.cmake
  CMake/unix_config.cmake
  src/tm2/controller_event_serializer.h
  third-party/libtm/libtm/src/CMakeLists.txt
  third-party/libtm/libtm/src/infra/Event_bsd.cpp
  third-party/libtm/libtm/src/infra/Event_lin.cpp
  third-party/libtm/libtm/src/infra/Event_win.cpp
  third-party/libtm/libtm/src/infra/Poller_bsd.cpp
  third-party/libtm/libtm/src/infra/Poller_lin.cpp
  third-party/libtm/libtm/src/infra/Poller_win.cpp
  third-party/libtm/libtm/src/infra/Utils.cpp
  third-party/libtm/tools/CMakeLists.txt
Labels: MacOS, T260 series, libtm

#3425 Update installation_osx.md
  doc/installation_osx.md
Labels: MacOS

#3484 Fix typo in raspbian installation
  doc/installation_raspbian.md
Labels: documentation

#3482 Connected get_motion_intrinsics API to get parameters for T265
  src/tm2/tm-device.cpp
Labels: T260 series

#3466 Fixing USB2 detection bug
  src/win/win-helpers.cpp
Labels: Windows

#3455 Trimming HID timestamps to 32bit
  src/ds5/ds5-timestamp.cpp
  unit-tests/CMakeLists.txt
Labels: d435i

#3459 [Python] Add CMake option to generate python documentation with Sphinx
  CMake/lrs_options.cmake
  wrappers/CMakeLists.txt
  wrappers/python/CMakeLists.txt
  wrappers/python/docs/CMake/FindSphinx.cmake
  wrappers/python/docs/CMakeLists.txt
  wrappers/python/docs/_templates/class.rst
  wrappers/python/docs/_templates/module.rst
  wrappers/python/docs/conf.py.in
  wrappers/python/docs/index.rst
  wrappers/python/python.cpp
Labels: documentation, python

#3462 renaming of wheel odometry API: uses translational velocity (measurem…
  include/librealsense2/h/rs_sensor.h
  include/librealsense2/hpp/rs_sensor.hpp
  src/core/motion.h
  src/rs.cpp
  src/tm2/tm-device.cpp
  src/tm2/tm-device.h
  third-party/libtm/libtm/include/TrackingData.h
  third-party/libtm/libtm/src/CompleteTask.h
  third-party/libtm/libtm/src/Device.cpp
  third-party/libtm/libtm/src/Message.h
  third-party/libtm/tools/libtm_util/libtm_util.cpp
  unit-tests/resources/calibration_odometry.json
  wrappers/csharp/Intel.RealSense/NativeMethods.cs
  wrappers/python/python.cpp
Labels: T260 series

#3521 T265: Check that stream index is 1 or 2 and throw an error if not
  src/tm2/tm-device.cpp
Labels: T260 series

#3535 unit-tests: separate wheel odometry unit test
  unit-tests/unit-tests-live.cpp
Labels: T260 series

#3513 Trajectory
  examples/CMakeLists.txt
  examples/readme.md
  examples/trajectory/CMakeLists.txt
  examples/trajectory/readme.md
  examples/trajectory/rs-trajectory.cpp
Labels: T260 series

#3547 android - device and device list added, fw version check added t the …
  src/android/CMakeLists.txt
  src/android/jni/context.c
  src/android/jni/device.c
  src/android/jni/device_list.c
  wrappers/android/examples/capture/src/main/java/com/intel/realsense/capture/MainActivity.java
  wrappers/android/examples/recording/src/main/java/com/intel/realsense/recording/MainActivity.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/CameraInfo.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Device.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DeviceCallback.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DeviceList.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/RsContext.java
  wrappers/android/tools/camera/src/main/java/com/intel/realsense/camera/DetachedActivity.java
Labels: android

#3551 changed conditions order to avoid segfault
  common/model-views.cpp
Labels: bug

#3515 T265 query devices fix
  examples/align/rs-align.cpp
  examples/example.hpp
  examples/measure/rs-measure.cpp
  examples/multicam/readme.md
  examples/multicam/rs-multicam.cpp
  examples/post-processing/rs-post-processing.cpp
  examples/sensor-control/helper.h
  include/librealsense2/hpp/rs_frame.hpp
  src/backend.h
  src/context.cpp
  src/context.h
  src/device_hub.cpp
  src/device_hub.h
  src/linux/backend-v4l2.cpp
  src/tm2/tm-context.cpp
  src/tm2/tm-context.h
  src/tm2/tm-conversions.h
  src/tm2/tm-device.cpp
  third-party/libtm/libtm/include/TrackingManager.h
  third-party/libtm/libtm/src/Device.cpp
  third-party/libtm/libtm/src/Manager.cpp
  third-party/libtm/libtm/src/Manager.h
  third-party/libtm/libtm/src/UsbPlugListener.cpp
  third-party/libtm/libtm/src/UsbPlugListener.h
  third-party/libtm/libtm/src/infra/Log.cpp
Labels: T260 series

#3449 Add minor version to soname
  CMakeLists.txt
  wrappers/python/CMakeLists.txt
Labels: Linux

#3577 More edits to matlab code in wrapper
  wrappers/matlab/align.m
  wrappers/matlab/frameset.m
  wrappers/matlab/points.m
Labels: matlab

#3578 [python] reorder enable_stream overload registration to fix overload registration
  wrappers/python/python.cpp
Labels: python

#3600 update Unity readme.md
  wrappers/unity/readme.md
Labels: documentation, unity
