Repository IntelRealSense/librealsense, pull requests merged in 2019-01, with the labels that each got.

#2990 T265 serial number fix
  src/tm2/tm-device.cpp
Labels: bug

#3005 Create installation_raspbian.md
  doc/installation_raspbian.md
Labels: Linux, documentation

#3008 Libtm library merge from 479c
  third-party/libtm/libtm/include/TrackingData.h
  third-party/libtm/libtm/include/TrackingDevice.h
  third-party/libtm/libtm/src/Device.cpp
  third-party/libtm/libtm/src/Device.h
  third-party/libtm/libtm/src/Manager.h
  third-party/libtm/libtm/src/Message.h
  third-party/libtm/libtm/src/infra/Semaphore_win.cpp
  third-party/libtm/tools/libtm_util/libtm_util.cpp
  third-party/libtm/versions.cmake
Labels: libtm

#3010 Pose stream info
  common/model-views.cpp
  common/model-views.h
  common/parser.hpp
  common/rendering.h
  include/librealsense2/rsutil.h
Labels: GUI, enhancement

#3035 T265 udev rules update
  config/99-realsense-libusb.rules
Labels: Linux, T260 series, bug

#3034 Code of Conduct
  code-of-conduct.md
Labels: documentation

#2997 Fix IMU Start-up delay on Linux
  CMake/global_config.cmake
  CMake/lrs_options.cmake
  src/archive.cpp
  src/linux/backend-hid.cpp
  src/linux/backend-hid.h
  src/sensor.cpp
  unit-tests/unit-tests-live.cpp
Labels: d435i

#3061 Pass ABI and STL settings to libusb CMake
  CMake/external_libusb.cmake
Labels: android

#3057 Adding threshold processing block
  examples/post-processing/rs-post-processing.cpp
  include/librealsense2/h/rs_processing.h
  include/librealsense2/hpp/rs_processing.hpp
  src/proc/CMakeLists.txt
  src/proc/threshold.cpp
  src/proc/threshold.h
  src/realsense.def
  src/rs.cpp
  wrappers/python/python.cpp
Labels: api_change

#3054 Extracting functionality out of rs.cpp into header files
  src/api.h
  src/proc/synthetic-stream.h
  src/realsense.def
  src/rs.cpp
Labels: api_change

#3056 Adding YUY to RGB capabilities to public API as a processing block.
  include/librealsense2/h/rs_processing.h
  include/librealsense2/hpp/rs_processing.hpp
  src/image.cpp
  src/image.h
  src/proc/CMakeLists.txt
  src/proc/yuy2rgb.cpp
  src/proc/yuy2rgb.h
  src/realsense.def
  src/rs.cpp
  wrappers/python/python.cpp
Labels: api_change

#3069 Update to definition of variable 'out' in align.m
  wrappers/matlab/align.m
Labels: matlab

#3071 Fix a comparison-instead-of-assignment bug.
  src/linux/backend-v4l2.cpp
  src/linux/backend-v4l2.h
Labels: Linux

#2954 Fixed the "must be a scalar" issue
  wrappers/matlab/config.m
Labels: matlab

#3025 fix nite2 support, fix intrinsics
  wrappers/openni2/src/Rs2Base.h
  wrappers/openni2/src/Rs2Commands.h
  wrappers/openni2/src/Rs2Device.cpp
  wrappers/openni2/src/Rs2Stream.cpp
  wrappers/openni2/src/Rs2Stream.h
  wrappers/openni2/src/Rs2StreamProps.cpp
  wrappers/openni2/src/XnDepthShiftTables.h
Labels: openni

#3103 Viewer grid support
  common/model-views.cpp
  common/model-views.h
  common/rendering.h
Labels: GUI, T260 series

#3132 Markdown Images case sensitive
  tools/rs-imu-calibration/README.md
Labels: documentation

#3161 IMU and Tracking sensors readme
  doc/img/LRS_CS_axis_base.png
  doc/img/T265_orientation_axis.png
  doc/img/t265_pose_orientation.png
  doc/img/t265_snapshot.png
  doc/img/t265_trajectory_tracker.gif
  doc/imu_and_tracking_sensors.md
  doc/readme.md
Labels: d435i, documentation, tracking

#3053 Motion Estimation
  examples/CMakeLists.txt
  examples/example.hpp
  examples/motion/CMakeLists.txt
  examples/motion/d435.h
  examples/motion/readme.md
  examples/motion/rs-motion.cpp
  examples/readme.md
Labels: d435i

#3162 Simple Python example for T265 pose stream
  wrappers/python/examples/t265_example.py
  wrappers/python/examples/tm2_example.py
  wrappers/python/python.cpp
Labels: T260 series, tracking
