Repository IntelRealSense/librealsense, pull requests merged in 2019-04, with the labels that each got.

#3610 Updated apt-get dependencies : xorg-dev libgtk-3-dev libusb-1.0-0-dev
  doc/installation_raspbian.md
Labels: documentation

#3646 Wheel odometry unit test fix up
  unit-tests/unit-tests-live.cpp
Labels: T260 series

#3522 T265: Add pose and image example for 200Hz pose + 30Hz images
  examples/CMakeLists.txt
  examples/pose-and-image/CMakeLists.txt
  examples/pose-and-image/readme.md
  examples/pose-and-image/rs-pose-and-image.cpp
  examples/readme.md
  examples/tracking.md
Labels: T260 series

#3571 [sample] roll-pitch-yaw from T265
  wrappers/python/examples/t265_rpy.py
Labels: T260 series, python

#3591 Realsense viewer multicamera T265 support
  common/model-views.cpp
  common/model-views.h
Labels: T260 series

#3541 Implements retrieving camera intrinsic parameters from T265
  include/librealsense2/h/rs_types.h
  include/librealsense2/rsutil.h
  src/tm2/tm-conversions.h
  src/tm2/tm-device.cpp
  src/types.cpp
  third-party/libtm/libtm/include/TrackingData.h
  third-party/libtm/libtm/src/Message.h
Labels: T260 series

#3593 Basic AR example with T265
  examples/CMakeLists.txt
  examples/ar-basic/CMakeLists.txt
  examples/ar-basic/coordinates.jpg
  examples/ar-basic/example.gif
  examples/ar-basic/readme.md
  examples/ar-basic/rs-ar-basic.cpp
  examples/example.hpp
  examples/readme.md
  examples/tracking.md
Labels: T260 series

#3643 Simplify udev-rules application
  doc/installation.md
  scripts/setup_udev_rules.sh
Labels: Linux, installation

#3641 Exit function after CUDA conversion
  src/image.cpp
Labels: cuda

#3634 [python] Pipeline callbacks
  wrappers/python/python.cpp
Labels: python

#3666 Release GIL in pipeline::wait_for_frames()
  wrappers/python/python.cpp
Labels: python

#3715 W10 support
  common/rendering.h
  examples/example.hpp
  include/librealsense2/h/rs_option.h
  include/librealsense2/h/rs_sensor.h
  src/core/streaming.h
  src/device.cpp
  src/device.h
  src/ds5/ds5-device.cpp
  src/ds5/ds5-factory.cpp
  src/ds5/ds5-private.h
  src/ds5/ds5-rolling-shutter.cpp
  src/image.cpp
  src/media/playback/playback_device.h
  src/media/record/record_device.h
  src/pipeline/config.cpp
  src/pipeline/config.h
  src/pipeline/resolver.h
  src/types.cpp
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/StreamFormat.java
Labels: api_change

#3775 Update t265.md: added odometry calibration information
  doc/t265.md
Labels: documentation

#3687 [Unity] Support linear color space
  wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RsStreamTextureRenderer.cs
Labels: unity

#3804 #3803 Removed the requirement of additional hid devices
  src/ds5/ds5-factory.cpp
Labels: MacOS, android, d435i

#3611 CMake improvements for Windows build
  .gitignore
  CMake/windows_config.cmake
Labels: Windows, cmake

#3869 Android - add missing filters to Java API
  src/android/jni/frame.cpp
  src/android/jni/processing.cpp
  wrappers/android/examples/processing/.gitignore
  wrappers/android/examples/processing/build.gradle
  wrappers/android/examples/processing/proguard-rules.pro
  wrappers/android/examples/processing/src/main/AndroidManifest.xml
  wrappers/android/examples/processing/src/main/java/com/intel/realsense/processing/MainActivity.java
  wrappers/android/examples/processing/src/main/res/layout-land/activity_main.xml
  wrappers/android/examples/processing/src/main/res/layout/activity_main.xml
  wrappers/android/examples/processing/src/main/res/values/attrs.xml
  wrappers/android/examples/processing/src/main/res/values/colors.xml
  wrappers/android/examples/processing/src/main/res/values/strings.xml
  wrappers/android/examples/processing/src/main/res/values/styles.xml
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Align.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DecimationFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/DisparityTransformFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Frame.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/FrameReleaser.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/FrameSet.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/HoleFillingFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Pointcloud.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/Points.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/SpatialFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/TemporalFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/ThresholdFilter.java
  wrappers/android/librealsense/src/main/java/com/intel/realsense/librealsense/ZeroOrderInvalidationFilter.java
  wrappers/android/settings.gradle
Labels: android
