Repository IntelRealSense/librealsense, pull requests merged in 2020-03, with the labels that each got.

#5929 Fix typo in `rs-ar-advanced.cpp`
  examples/ar-advanced/rs-ar-advanced.cpp
Labels: documentation

#5853 Distortion model in csharp
  wrappers/csharp/Intel.RealSense/Types/Enums/Distortion.cs
Labels: .NET

#5655 Add vcpkg installation instructions
  readme.md
Labels: documentation

#5579 Updated T parameters in rotated camera odometry example.
  doc/t265.md
Labels: T260 series

#5333 Software Device update
  include/librealsense2/h/rs_internal.h
  include/librealsense2/h/rs_sensor.h
  include/librealsense2/h/rs_types.h
  include/librealsense2/hpp/rs_internal.hpp
  include/librealsense2/hpp/rs_sensor.hpp
  include/librealsense2/hpp/rs_types.hpp
  src/media/playback/playback_sensor.cpp
  src/media/playback/playback_sensor.h
  src/option.h
  src/realsense.def
  src/rs.cpp
  src/sensor.cpp
  src/sensor.h
  src/software-device.cpp
  src/software-device.h
  src/types.h
  unit-tests/unit-tests-live.cpp
  wrappers/python/c_files.cpp
  wrappers/python/pyrs_device.cpp
  wrappers/python/pyrs_internal.cpp
  wrappers/python/pyrs_types.cpp
  wrappers/python/python.cpp
  wrappers/python/python.hpp
Labels: api_change

#5622 C# Wrapper Reference Counting for Sensor/Device
  wrappers/csharp/Intel.RealSense/Base/CMakeLists.txt
  wrappers/csharp/Intel.RealSense/Base/RefCountedPooledObject.cs
  wrappers/csharp/Intel.RealSense/Devices/Device.cs
  wrappers/csharp/Intel.RealSense/Sensors/Sensor.cs
Labels: .NET

#5988 Fix default USB permissions for T265 (Android)
  wrappers/android/librealsense/src/main/res/xml/usb_filter.xml
Labels: T260 series, android

#5970 Additions to matlab bindings
  wrappers/matlab/advanced_mode.m
  wrappers/matlab/advanced_mode_example.m
  wrappers/matlab/device.m
  wrappers/matlab/frame_queue.m
  wrappers/matlab/librealsense_mex.cpp
  wrappers/matlab/pipeline.m
  wrappers/matlab/rs2_type_traits.h
  wrappers/matlab/syncer.m
Labels: matlab

#6026 OpenVINO face detection as part of realsense-viewer
  common/model-views.cpp
  common/model-views.h
  common/objects-in-frame.h
  common/post-processing-block-model.h
  common/post-processing-filter.h
  common/post-processing-filters-list.h
  common/post-processing-worker-filter.h
  common/processing-block-model.h
  common/viewer.cpp
  tools/depth-quality/depth-quality-model.cpp
  tools/realsense-viewer/CMakeLists.txt
  tools/realsense-viewer/openvino-face-detection.cpp
  tools/realsense-viewer/realsense-viewer.cpp
  wrappers/opencv/cv-helpers.hpp
  wrappers/openvino/CMakeLists.txt
  wrappers/openvino/dl_vino_model.cmake
  wrappers/openvino/rs-vino/age-gender-detection.cpp
  wrappers/openvino/rs-vino/age-gender-detection.h
  wrappers/openvino/rs-vino/detected-object.h
Labels: openvino

#6095 Fixed bug on get_resolution_from_width_height() on l400-depth
  src/l500/l500-depth.cpp
Labels: bug, l500

#6040 Updating the script to run cleanly on Raspbian
  scripts/libuvc_installation.sh
Labels: raspberry pi

#6000 Added HW sync enable control for L515
  include/librealsense2/h/rs_option.h
  src/l500/l500-device.cpp
  src/l500/l500-private.cpp
  src/l500/l500-private.h
  src/option.h
  wrappers/nodejs/src/addon.cpp
  wrappers/unrealengine4/Plugins/RealSense/Source/RealSense/Public/RealSenseTypes.h
Labels: l500

#6119 Update python wrapper to fix save_to_ply options
  wrappers/python/python.cpp
Labels: python

#6118 [swdev] Add API to break circular dependency with Active Object
  include/librealsense2/h/rs_internal.h
  include/librealsense2/hpp/rs_internal.hpp
  src/realsense.def
  src/rs.cpp
Labels: api_change

#6145 Small fixes for realsense-viewer with OpenVINO
  common/post-processing-filters-list.h
  tools/realsense-viewer/realsense-viewer.cpp
Labels: openvino
